/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro Padilla
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setIconImage(getIconImage());
        setTitle("Puntualify");
    }
    
    @Override
    public Image getIconImage() {
    // Accede a la imagen en la carpeta resources
        Image retValue = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LogoPOO.png"));
    return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EditEmp = new javax.swing.JButton();
        RepAsis = new javax.swing.JButton();
        ConfSeg = new javax.swing.JButton();
        ComRegis = new javax.swing.JButton();
        SalBut = new javax.swing.JButton();
        ButPerfilBiometrico = new javax.swing.JButton();
        ButTraining = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EditEmp.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        EditEmp.setText("Gestion Perfiles");
        EditEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEmpActionPerformed(evt);
            }
        });
        jPanel1.add(EditEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 30));

        RepAsis.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        RepAsis.setText("Registro de Asistencia");
        RepAsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepAsisActionPerformed(evt);
            }
        });
        jPanel1.add(RepAsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, 30));

        ConfSeg.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        ConfSeg.setText("Configuracion seguridad");
        ConfSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfSegActionPerformed(evt);
            }
        });
        jPanel1.add(ConfSeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, 30));

        ComRegis.setBackground(new java.awt.Color(255, 102, 0));
        ComRegis.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        ComRegis.setText("Comenzar registro de asistencia");
        ComRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComRegisActionPerformed(evt);
            }
        });
        jPanel1.add(ComRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 330, 80));

        SalBut.setBackground(new java.awt.Color(255, 102, 0));
        SalBut.setText("X");
        SalBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalButActionPerformed(evt);
            }
        });
        jPanel1.add(SalBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 70, 70));

        ButPerfilBiometrico.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ButPerfilBiometrico.setText("Crear Perfil Biometrico");
        ButPerfilBiometrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButPerfilBiometricoActionPerformed(evt);
            }
        });
        jPanel1.add(ButPerfilBiometrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 190, 30));

        ButTraining.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ButTraining.setText("Entrenar Modelo");
        ButTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButTrainingActionPerformed(evt);
            }
        });
        jPanel1.add(ButTraining, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alejandro Padilla\\Documents\\Programacion\\POO\\ProyectoFinal\\DataBase\\BDRegistro\\BDRegistro\\src\\main\\java\\Imagenes\\MenuOriginalSize.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jLabel2.setText("jLabel1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEmpActionPerformed
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormPrincipal EditEmple = new FormPrincipal();
                EditEmple.setVisible(true);
                EditEmple.setLocationRelativeTo(null);
                dispose();
                
            }
        });
    }//GEN-LAST:event_EditEmpActionPerformed

    private void ConfSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfSegActionPerformed
        Seguridad seg = new Seguridad();
        seg.setVisible(true);
        seg.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_ConfSegActionPerformed

    private void SalButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalButActionPerformed
        Formularios.LogIn Inicio = new Formularios.LogIn();
        Inicio.setVisible(true);
        Inicio.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_SalButActionPerformed


    private void ButPerfilBiometricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButPerfilBiometricoActionPerformed
        dispose();
        ProcessBuilder pb = new ProcessBuilder("python", "C:\\Users\\Alejandro Padilla\\Documents\\Programacion\\POO\\Sistema-de-Reconocimiento-Facial\\CapturaImagenes.py");
                pb.directory(new File("C:\\Users\\Alejandro Padilla\\Documents\\Programacion\\POO\\Sistema-de-Reconocimiento-Facial"));
                try {
                    Process p = pb.start();
                    // Wait for the Python script to finish executing
                    int exitCode = p.waitFor();
                    if (exitCode == 0) {
                        // Python script finished successfully
                        Menu menu = new Menu();
                        menu.setVisible(true);
                        menu.setLocationRelativeTo(null);
                        
                    } else {
                        // Python script failed with an error
                        JOptionPane.showMessageDialog(null, "Python script failed with error code " + exitCode);
                    }
                } catch (Exception ex) {
                    System.err.println("Error running Python script: " + ex.getMessage());
                }
    }//GEN-LAST:event_ButPerfilBiometricoActionPerformed

    private void ButTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButTrainingActionPerformed
        dispose();
        ProcessBuilder pb = new ProcessBuilder("python", "C:\\Users\\Alejandro Padilla\\Documents\\Programacion\\POO\\Sistema-de-Reconocimiento-Facial\\TrainingFR.py");
                pb.directory(new File("C:\\Users\\Alejandro Padilla\\Documents\\Programacion\\POO\\Sistema-de-Reconocimiento-Facial"));
                try {
                    Process p = pb.start();
                    // Wait for the Python script to finish executing
                    int exitCode = p.waitFor();
                    if (exitCode == 0) {
                        // Python script finished successfully
                        Menu menu = new Menu();
                        menu.setVisible(true);
                        menu.setLocationRelativeTo(null);
                        
                    } else {
                        // Python script failed with an error
                        JOptionPane.showMessageDialog(null, "Python script failed with error code " + exitCode);
                    }
                } catch (Exception ex) {
                    System.err.println("Error running Python script: " + ex.getMessage());
                }
    }//GEN-LAST:event_ButTrainingActionPerformed

    private void RepAsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepAsisActionPerformed
       dispose();
        ProcessBuilder pb = new ProcessBuilder("python", "C:\\Users\\Alejandro Padilla\\Documents\\Programacion\\POO\\Sistema-de-Reconocimiento-Facial\\GestAsistencia.py");
                pb.directory(new File("C:\\Users\\Alejandro Padilla\\Documents\\Programacion\\POO\\Sistema-de-Reconocimiento-Facial"));
                try {
                    Process p = pb.start();
                    // Wait for the Python script to finish executing
                    int exitCode = p.waitFor();
                    if (exitCode == 0) {
                        // Python script finished successfully
                        Menu menu = new Menu();
                        menu.setVisible(true);
                        menu.setLocationRelativeTo(null);
                        
                    } else {
                        // Python script failed with an error
                        JOptionPane.showMessageDialog(null, "Python script failed with error code " + exitCode);
                    }
                } catch (Exception ex) {
                    System.err.println("Error running Python script: " + ex.getMessage());
                }
    }//GEN-LAST:event_RepAsisActionPerformed


    private void ComRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComRegisActionPerformed
        dispose();
        ProcessBuilder pb = new ProcessBuilder("python", "C:\\Users\\Alejandro Padilla\\Documents\\Programacion\\POO\\Sistema-de-Reconocimiento-Facial\\DifRostros.py");
                pb.directory(new File("C:\\Users\\Alejandro Padilla\\Documents\\Programacion\\POO\\Sistema-de-Reconocimiento-Facial"));
                try {
                    Process p = pb.start();
                    // Wait for the Python script to finish executing
                    int exitCode = p.waitFor();
                    if (exitCode == 0) {
                        // Python script finished successfully
                        Menu menu = new Menu();
                        menu.setVisible(true);
                        menu.setLocationRelativeTo(null);
                        
                    } else {
                        // Python script failed with an error
                        JOptionPane.showMessageDialog(null, "Python script failed with error code " + exitCode);
                    }
                } catch (Exception ex) {
                    System.err.println("Error running Python script: " + ex.getMessage());
                }
    }//GEN-LAST:event_ComRegisActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButPerfilBiometrico;
    private javax.swing.JButton ButTraining;
    private javax.swing.JButton ComRegis;
    private javax.swing.JButton ConfSeg;
    private javax.swing.JButton EditEmp;
    private javax.swing.JButton RepAsis;
    private javax.swing.JButton SalBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
