/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Clases.SegurLogica;

public class Seguridad extends javax.swing.JFrame {
    
    SegurLogica security = new SegurLogica();
    public Seguridad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NameUser = new javax.swing.JLabel();
        EstContra = new javax.swing.JLabel();
        ConfContra = new javax.swing.JLabel();
        Usertxt = new javax.swing.JTextField();
        Passtxt1 = new javax.swing.JPasswordField();
        Passtxt2 = new javax.swing.JPasswordField();
        ButConf = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());


        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameUser.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        NameUser.setText("Nombre del usuario");
        jPanel1.add(NameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 160, -1));

        EstContra.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        EstContra.setText("Establecer contraseña");
        jPanel1.add(EstContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 150, -1));

        ConfContra.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        ConfContra.setText("Confirmar contraseña");
        jPanel1.add(ConfContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 150, -1));

        Usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsertxtActionPerformed(evt);
            }
        });
        jPanel1.add(Usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 300, 20));
        jPanel1.add(Passtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 238, 300, 20));
        jPanel1.add(Passtxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 312, 300, -1));


        ButConf.setBackground(new java.awt.Color(255, 102, 0));
        ButConf.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        ButConf.setText("Confirmar cambios");
        ButConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButConfActionPerformed(evt);
            }
        });
        jPanel1.add(ButConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 390, 300, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alejandro Padilla\\Documents\\Programacion\\POO\\ProyectoFinal\\DataBase\\BDRegistro\\BDRegistro\\src\\main\\java\\Imagenes\\16.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));


        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsertxtActionPerformed
        
    }//GEN-LAST:event_UsertxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu menuMain = new Menu();
        menuMain.setVisible(true);
        menuMain.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButConfActionPerformed
        security.CambiaContra(Usertxt,Passtxt1,Passtxt2);
    }//GEN-LAST:event_ButConfActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButConf;
    private javax.swing.JLabel ConfContra;
    private javax.swing.JLabel EstContra;
    private javax.swing.JLabel NameUser;
    private javax.swing.JPasswordField Passtxt1;
    private javax.swing.JPasswordField Passtxt2;
    private javax.swing.JTextField Usertxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
